### ISSUE TITLE
Stand up project infrastructure

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#104]
Currently, the project has no automated tests, no way to know whether the commit broke the build, or a way to track failures. We need all of that.

Anyone who's familiar with running TS monorepos should be able to quickly build something useful here.

**Comment by SampathKumar27896** [comment]
Hmm..Is it that we need to add the test command on the main package.json file?.  Or I would like to know more in detail.

**Comment by dglazkov** [comment]
I am seeing a couple of things:

- [ ] Document project practices (fix-forward mindset, pitch in when broken, code review optional)
- [ ] Teach github to run `npx turbo test` on each commit.
- [ ] ... something of that nature?

**Comment by dglazkov** [comment]
Since we are "code review optional", it would be super-nice to see very quickly whe a commit breaks the build on `main`.

**Comment by SampathKumar27896** [comment]
Hi Dimitri, got an understanding of the above mentioned requirements. I would like to take up the issue and start working on this.

**Comment by dglazkov** [comment]
Declaring victory 🥳
