### ISSUE TITLE
Implement edge queueing

### ISSUE THREAD

**Issue by seefeldb** [google/labs-prototypes#108]
Right now if a node is receiving two rounds of data before being called (e.g. because it is being populated out of a loop), it appears that some of those values can be dropped. This isn't quite intuitive.

Some options are:
- Keep the current behavior and add tools to control the behavior so that this doesn't happen. #99 is one idea. Often `passthrough` nodes do the job as well.
- Throw an error if this happens, either right then or with other checks after running a graph, like noting other nodes that were waiting with partial inputs and never ran.
- Change behavior to queueing by default and make overwriting inputs an optional behavior.
- Add a linter to detect these cases.
- If there are multiple ways to schedule calling nodes and only one doesn't leave data stranded, do that (follow-up questions: If there are multiple ones, do they result in different behavior or do they all have equivalent outcomes?)

Queueing appears to me to be the most straightforward one. And queuing is what one would expect of anything looking a streams, so it might be sensible to assume this behavior, even if we later add special stream types for high-bandwidth media. See #38. There is a lot of prior work here.

There's still some scenarios left where data can get stranded, e.g. when two incoming wires are required and the quantity doesn't match. We could try to catch these with pre-run linting or show warnings if a graph runs and still has pending data stuck somewhere at the end.

FWIW: Special casing overwriting inputs corresponds to introducing a Last-Write-Wins CRDT. This, like other CRDTs, is useful when we have changing source state and are aiming for eventual consistency.

**Comment by dglazkov** [comment]
I'd love to try queueing and see if it will change behavior of our existing boards dramatically.
