### ISSUE TITLE
Generate API documentation

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#114]
We're at a point now where we could start generating API documentation.

Something like https://tsdoc.org/ might be nice, or any other better alternatives.

Also need to figure out where and how to host it.

**Comment by Chizobaonorh** [comment]
Hello i would love to contribute to this.

**Comment by dglazkov** [comment]
@Chizobaonorh amazing! I haven't looked at how it's done, but it should be fairly straightforward to get something simple going. I am primarily interested in the API docs for `seeds/breadboard` and `seeds/llm-starter` packages for now.

**Comment by Chizobaonorh** [comment]
Does this use rest API?

**Comment by dglazkov** [comment]
Not at the moment. The API surface is all TypeScript.

**Comment by Chizobaonorh** [comment]
okay so how do i get started with this @dglazkov

**Comment by dglazkov** [comment]
I am not sure myself! Lots of learning ahead 😄  
I would break this down into a couple of smaller tasks.

- [ ]  First, I would learn about [tsdoc](https://tsdoc.org/) and how it works.
- [ ] Then, I would try to run tsdoc on the repository and see what it generates
- [ ] Then, I'd fiddle a lot with configuring it to make sure it does what I want
- [ ] ...

Does that help?

**Comment by Chizobaonorh** [comment]
Uhm... Is there any setup i need to do on my system to get this running, or i simply just fork, edit and commit changes?

**Comment by Chizobaonorh** [comment]
And how do i go about testing the API to be able to document the processes?
And does this API need a getting started page, or you are solely focused on documenting the endpoints?

**Comment by dglazkov** [comment]
> Uhm... Is there any setup i need to do on my system to get this running, or i simply just fork, edit and commit changes?

There is a bit of a setup (typical for a node.js project) and a few notes on the "happy path" for a developer, documented here:
https://github.com/google/labs-prototypes/blob/main/DEVELOPING.md
 
> And how do i go about testing the API to be able to document the processes? And does this API need a getting started page, or you are solely focused on documenting the endpoints?

I would start here:
https://github.com/google/labs-prototypes/tree/main/seeds/graph-playground#readme

This project is in its very early stages, and there's still a lot to be done to organize and make it friendly for contributors. Apologies for the construction dust 🚧

**Comment by Chizobaonorh** [comment]
Okay thank you very much, i will get started with these.

**Comment by dglazkov** [comment]
Oh, almost forgot! https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/docs/tutorial/README.md is a nice tutorial for Breadboard.

**Comment by Chizobaonorh** [comment]
Thank you so so much, this is enough to get me started, i would communicate further questions to you.

**Comment by Chizobaonorh** [comment]
Okay i have gone through this links you sent.
Let me better clarify this.
You want me to write down the documentations for seeds/breadboards and seed/llm starter and also find a perfect hosting for the other documentations already provided on your site right?

**Comment by Chizobaonorh** [comment]
And i also realized that in the seeds/breadboard there is an endpoint.md folder, I would love to use Swagger Ui to write and host alongside with github pages your endpoints, but there is no link to accessing the endpoints, so can you assist with that.

**Comment by dglazkov** [comment]
> You want me to write down the documentations for seeds/breadboards and seed/llm starter and also find a perfect hosting for the other documentations already provided on your site right?

Generate the documentation, not write it. Each method, class, or function that are part of the API already have the necessary documentation as part of its comments. For example, see:

https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/src/board.ts#L70

These comments are written in a special way -- they are compatible with the TSDoc tool. Running the tool over these files generates the documentation.

Once we can do that, we can check and see what comments are still missing, then add them and generate again.

> You want me to write down the documentations for seeds/breadboards and seed/llm starter and also find a perfect hosting for the other documentations already provided on your site right?

Let's start with the generation first. Once we have the generated docs, we'll figure out the next steps.

Does that make sense?

**Comment by Chizobaonorh** [comment]
ohh i get it now, okay on it.

**Comment by Chizobaonorh** [comment]
Tsdoc uses Jekyll to generate its documentation and i am working on using that for this too, i would keep you updated on how it is going.

**Comment by dglazkov** [comment]
@Chizobaonorh if you have any questions, ask away. If you prefer chat format, you can join https://discord.gg/breadboard

**Comment by Chizobaonorh** [comment]
The markdown homepage of this API is under the tag name of what, because i can seem to locate a file name with just index.html.

**Comment by Chizobaonorh** [comment]
@dglazkov I just finished working on generating and hosting the documentation and I have created a pull request with the uodates.

**Comment by dglazkov** [comment]
Closing this one as fixed in https://github.com/google/labs-prototypes/commit/704732c0c4d5dd035d55880b9b5e01cad4b70a07
