### ISSUE TITLE
Write a web app with UI that uses graph traversal

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#12]
Write something that is a web app that actually relies on the graph to function.

**Comment by dglazkov** [comment]
There are two nodes that will give us trouble currently: `run-javascript` (because it assumes NodeVM being available) and `text-asset` (because it assumes Node file access package being available)

I think for now, it's fine to hack around this, but we'll need a more permanent solution soon.

@proales

**Comment by dglazkov** [comment]
Split off #43 and #42.

**Comment by dglazkov** [comment]
Added #50 .

**Comment by PaulKinlan** [comment]
Also - `fetch` node will hit CORS issues in the browser.

**Comment by dglazkov** [comment]
@PaulKinlan  did it!
