### ISSUE TITLE
Introduce support for `$error` outputs

### ISSUE THREAD

**Issue by seefeldb** [google/labs-prototypes#129]
As a strategy for implementing error handling #96, simply
 - add a convention that errors should lead to an `$error` output,
 - treat uncaptured `$error` outputs as an error at the graph level, and
 - automatically convert exceptions from within a node to `$error` outputs (thus recovering current behavior when `$error` isn't captured).

This distinction is most useful when
 - errors are often expected (because for instance inputs can be irregular) and there is a well-defined handling strategy (showing something to the user or so)
 - LLM self-correcting loops where we feed the error back to the LLM and try again

In nested graphs, the `include` (or soon `call`) node outputs `$error` if it catches and uncaptured `$error` in the called graph.

Uncaptured errors handled in this way should be annotated with the (in the nested case:) graphs and node-ids of the source.

**Comment by dglazkov** [comment]
I _really_ like this.

**Comment by seefeldb** [comment]
About to submit with a little addition. $error are of type `ErrorCapacity`, which have
- `error` – `instanceof Error` that was caught
- `inputs` – Original inputs of the node
- `descriptor` – Metadata about the node

The latter two are automatically added when a node outputs `$error` and they aren't already specified.

This should help with retrying flows, as otherwise the `inputs` would already be consumed and now lost. I'm adding `descriptor` for debugging context, but it might eventually be helpful when we for instance catch errors at a lambda level and retry with a new version of the lambda written by an LLM.

**Comment by seefeldb** [comment]
I'm also changing the error behavior of `generateText`:

Before it didn't output `completion`, but output `filters`. This let to silent aborts of graphs, as the subsequent nodes were missing inputs and nothing was looking at `filters`.

Now it'll either output `completion` or `$error`, the latter with `filters` and `safetyFeedback`.

I suggest we generally adopt this pattern for nodes that have an expected positive outcome and otherwise negative outcomes.
