### ISSUE TITLE
Implement API documenting workflow

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#134]
As of https://github.com/google/labs-prototypes/commit/704732c0c4d5dd035d55880b9b5e01cad4b70a07 and thanks to @Chizobaonorh, we now have a way to generated API documentation.

The next step is to establish a workflow that enables any contributor to the project to quickly and easily update API documentation. The primary purpose of this workflow is to reduce barriers to keeping the API documentation up to date.

Here's a sketch of the workflow for a developer contributor when it is implemented:

1. Developer writes new code
2. Adds or changes [TSDoc](https://tsdoc.org/) comments to their code
3. Runs a single command (probably `npx turbo generate:docs`) to update documentation
4. Submits updated documentation with their code PR.

Here's how the same workflow will work for a tech writer contributor:

1. Tech Writer examines existing API documentation
2. Finds a problem: typo, grammar, missing/obsolete information, etc.
2. Adds or changes [TSDoc](https://tsdoc.org/) comments to fix the problem
3. Runs a single command (probably `npx turbo generate:docs`) to update documentation
4. Submits updated documentation as a PR.

Here are the tasks to get there:

- [x] Implement `npm run generate:docs` command for each package in `/seeds/`
- [ ] Implement `npx turbo generate:docs` command
- [x] Update `DEVELOPING.md` with documentation on how to use these commands to update generated API docs.

**Comment by Chizobaonorh** [comment]
Okay i can adequately handle these tasks

**Comment by dglazkov** [comment]
@Chizobaonorh it sounds like the only thing left here is implementing `npx turbo generate:docs` command. That should be a fairly simple change to `turbo.json`. Look at how other commands are implemented and mimic that.

**Comment by Chizobaonorh** [comment]
> @Chizobaonorh it sounds like the only thing left here is implementing `npx turbo generate:docs` command. That should be a fairly simple change to `turbo.json`. Look at how other commands are implemented and mimic that.

How do i access these other commands?

**Comment by dglazkov** [comment]
The `turbo` commands are specified in the `turbo.json` file. For example, one command is `test`:

```json
    "test": {
      "dependsOn": ["build", "^test"]
    }
```

What these three lines specify is that when you type in `npx turbo test`, it will first run the `build` command, then `test` commands for all package dependencies.

This is probably what you need to copy. Once you have it copied, try running `npx turbo generate:docs` at the root of the repository and see if the output shows lots of `npm run generate:docs` for all packages. If it does -- congrats! -- you've done it.

**Comment by dglazkov** [comment]
For more information on the `turbo.json` format, see https://turbo.build/repo/docs/reference/configuration#pipeline

**Comment by Chizobaonorh** [comment]
> For more information on the `turbo.json` format, see https://turbo.build/repo/docs/reference/configuration#pipeline

Hello, apologies for the late response, i will get to work on it

**Comment by dglazkov** [comment]
> apologies for the late response

All good! No need to apologize. Thank you for pitching in!

**Comment by dglazkov** [comment]
Whoops, reopening. My bad 😆

**Comment by Chizobaonorh** [comment]
I think we can successfully close off this task.

**Comment by Chizobaonorh** [comment]
We still have things to work on here? @dglazkov
