### ISSUE TITLE
Update tutorial for M3

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#199]
There's been a lot of changes to kit structures and other call sites between M2 and M3. We need to make sure the tutorial stays up to date.

**Comment by dglazkov** [comment]
🚢  Declaring victory

**Comment by aomarks** [comment]
There's still some work to do here :) Need to run through some more sections and also check all the checked-in `.js` files.

**Comment by aomarks** [comment]
Replits are also now updated.
