### ISSUE TITLE
Should we remove `/seeds/web-demo`

### ISSUE THREAD

**Issue by PaulKinlan** [google/labs-prototypes#204]
It was the original idea for a REPL (although graph based) that has been pretty much replaced by `/seeds/breadboard-web`

Happy to remove it as I don't see it being used anymore.

**Comment by dglazkov** [comment]
What are the things that it has that we still don't have in `breadboard-web`? Let's create a task list to migrate them and then yes.

**Comment by PaulKinlan** [comment]
The major one is the UI to edit the graph directly and instantly see the mermaid diagram.

**Comment by PaulKinlan** [comment]
Quick update - I'm going to delete this folder.
