### ISSUE TITLE
Support multimodal input

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#205]
Reading over https://platform.openai.com/docs/guides/vision, it seems like there's a new trend toward multimodal inputs. From the API docs:

```json
"content": [
  {
    "type": "text",
    "text": "What’s in this image?"
  },
  {
    "type": "image_url",
    "image_url": {
    "url": "data:image/jpeg;base64,{base64_image}"
  }
}
```

Let's teach Breadboard to support such inputs!

**Comment by dglazkov** [comment]
My intuition here is to make the [input](https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/src/ui/input.ts) UI control do all the heavy lifting. Basically, if we specify:

```json
{
  "type": "object", 
  "format": "multipart"
}
```
in the input schema, it will start acting as a multipart UI control: allow adding multiple parts within the input. Image parts and text part, for the moment.

Once submitted, the input will turn them into a JSON object that then could be formatted into the right shape with JSONata or plain JS.

**Comment by dglazkov** [comment]
@paullewis ^^^

**Comment by paullewis** [comment]
Yes! 👍🏻

**Comment by dglazkov** [comment]
Basic and barely working implementation is in. We will polish it up as we go along.

For information purposes, here's the graph that uses multipart input:
https://github.com/google/labs-prototypes/blob/main/seeds/breadboard-web/src/boards/openai-gpt-4-vision.ts
