### ISSUE TITLE
De-dash names

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#22]
I started with all names having a `dash-separated-convention`, and now I see that this was a mistake: instead of `foo.api_key`, I have to do `foo["api-key"]`, which looks inelegant. Let's switch all node types and inputs/outputs to use underscores instead.

**Comment by dglazkov** [comment]
Hi @SampathKumar27896! We're not yet set up for external contributors. The project is still in very early stages, and most of the governance bits are still developing. I will ping this bug as soon as we have the contributor process figured out.

**Comment by seefeldb** [comment]
@dglazkov let's decide which way we go for the M0 milestone.

**Comment by dglazkov** [comment]
Looking at https://github.com/google/labs-prototypes/blob/main/seeds/llm-starter/README.md, it seems like matching node type names to JS convention (`camelCase`) is a no-brainer... right?

**Comment by seefeldb** [comment]
Nice, let's do that. Also for the inputs and outputs. Maybe `API_KEY` & co as exception, since that's how `.env` is typically set up.

**Comment by dglazkov** [comment]
> _The project is still in very early stages, and most of the governance bits are still developing_ -- understood. _I will ping this bug as soon as we have the contributor process figured out._ -- Sure thanks.

@SampathKumar27896, if you're still interested in contributing, please check out the [contributing.md](https://github.com/google/labs-prototypes/blob/main/docs/contributing.md) doc. I believe we have most things in place to let you start submitting pull requests.

**Comment by SampathKumar27896** [comment]
Yeah sure I am looking forward to contribute, need to go through the guidelines and the recent dev updates to get an understanding as you said. Thanks for the update. :)
