### ISSUE TITLE
Be less `unknown` about JSON data

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#24]
Currently, both `InputValues` and `OutputValues` are defined as `Record<string, unknown>`, and that is probably too vague. We should specify `JSONValue` and use that instead of `unknown`.

**Comment by dglazkov** [comment]
Started in https://github.com/google/labs-prototypes/compare/main...json-in-outs

**Comment by dglazkov** [comment]
Related:
- #91
- #86

**Comment by dglazkov** [comment]
@seefeldb it looks like there are two kinds of things that we may want to pass:
- **handles**, where data is a reference to an object, as in [EmbedStringInputs](https://github.com/google/labs-prototypes/blob/7e0d37592e0e1ecf7e5749c261ebe9edfb958505/seeds/node-nursery/src/nodes/embed-string.ts)
- **blobs**, where the data is just binary data.

Does that seem right?

**Comment by seefeldb** [comment]
Yes, and the handles are often capabilities.

Streams might be another kind with special behavior down the road. I mean streams beyond repeatedly calling with new data on the wire, for example a (lossy?) video stream.
