### ISSUE TITLE
Inputs that bubble up

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#252]
Especially when composing boards, there are many situations where the invoked board might need additional inputs to the ones that are already provided via wires.

The prototypical example: 

- A Tour Guide Writer board takes another board as its Generator input, and invokes it, expecting that board to have the following inputs:
    -  `text` -- the text prompt to generate from
    - `useStreaming` -- the boolean to whether to use streaming or not (set to `false` in by the Tour Guide Writer board)
- Any board that has these two inputs (or even just the single `text` input) would be correctly invoked and run.

The problem:
- Now, suppose that we have an `Ominbus Text Generator` board, which matches the required inputs, but has another input in addition: the `model` board to choose one of many models that the omnibus wraps.
- Currently, this extra input results in a failure: the invoking Tour Guide Writer board can't supply the input it's not aware of.

The proposed solution:
- What we would like to happen instead is for such input requests to **bubble up**: to go up the stack of invoked boards and see if there's any way it could be fulfilled.
- In this case, the extra input will no longer cause a failure. When run in `breadboard-web`, for example, the user will simply see an extra input pop up asking for a model, and once the selection is made, the board will continue on its merry way.
- Similarly, if Tour Guide Writer board is invoked by another board, this invoked board can supply it as a wire or leave it to keep bubbling up to the user or environment.

This solution has a significant implication for the future of the `secrets` node. With input bubble-up enabled, we no longer need a special `secrets` node that a user must wire. Instead, it is an input node that has its format marked as `secret` and it bubbles up until provided by the user (or read from environment variables, when running from command line)

**Comment by dglazkov** [comment]
Sketch of a design:

To enable bubbling up, we teach the `input` node to recognize two interlocked state parameters:
- **required** - when `true`, the board indicates that this input must be wired in. When `false`, the input can be provided via bubbling up. If not specified, assumed to be `false`.
- **default** -- the default value for the input.

These two parameters form this matrix of behavior. "Fail" means throwing an error (this is different from the current behavior, where the value is treated as missing input for outgoing edges.

| Required | true | false |
|----|----|----|
|Has default|  Fail if input is not wired into an invocation. Use the default value to pre-fill the UI for the user when in top context  | Bubble up the input, if bubbling up fails to deliver the value, use the default |
| Has no default | Fail if input is not wired into an invocation  | Bubble up the input, fail if bubbling up fails. |

Both of these parameters are specified via the `schema` input of the `input` node. The **required** value is computed from `Schema.required` array, and the **default** value uses `Schema.default` of the corresponding property.

**Comment by dglazkov** [comment]
>  I'm scared of namespace collisions here

Me tooo. I think I will rely on the conventions and ingenuity of the developers for now. It could be both a feature and a bug to pick up an input by the same name 🤷🏻

**Comment by seefeldb** [comment]
what do you think of all uppercase as convention? (it's not user-visible, just developer-visible)

**Comment by dglazkov** [comment]
> all uppercase as convention

SGTM, I will start using it.

**Comment by dglazkov** [comment]
This mostly works now. Will hunt bugs as they appear.

**Comment by dglazkov** [comment]
https://www.youtube.com/watch?v=hSBXL7Q3Nhs for a quick demo

**Comment by dglazkov** [comment]
Observations on the convention: UPPERCASE names seem to be very useful for secret-like inputs, but not so much for truly optional inputs, like temperature or candidate count. So maybe the guidance on the convention is: use UPPERCASE for secret-like optional inputs.

**Comment by seefeldb** [comment]
Those have default values, though, and wouldn't bubble up, right? I.e. if not specified, we don't want to ask the user?

**Comment by dglazkov** [comment]
🚢  Declaring victory
