### ISSUE TITLE
Rename `reflect` to `meta`

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#37]
The `reflect` node is actually the `meta` node: it provides meta information about the graph and graph traversal process.

For example, we'll need a scope identifier that helps scoping `localMemory` to a graph -- and that's where the `meta` node comes in.

**Comment by seefeldb** [comment]
Can you elaborate on your thoughts on scope? 

(I'm thinking on how to support include/slot in the safety work, and something scope shaped appears there as well, if at first just to namespace the node IDs)

**Comment by dglazkov** [comment]
Yes! Scopes seem valuable when the graph contains multiple sub-graphs, included and slotted. There needs to be a way to help a node orient where it is, or at least have some identifier (scope!) that is like a zipcode for its own graph.

**Comment by dglazkov** [comment]
Not sure we need to do this anymore.
