### ISSUE TITLE
[Working log] Attempting to build a web app that uses graph-*

### ISSUE THREAD

**Issue by PaulKinlan** [google/labs-prototypes#51]
For Dimitri. This is a working log of all the issues I hit trying to get things working in the browser.

Goal 1: Build a web app that uses palm-lite
Goal 2: Build a web app that creates a breadboard programatically and runs it (using Starter Kit)
Goal 3: Build a web app that loads a graph and shows the mermaid view
Goal 4: Build a web app that loads a graph and runs it.
Goal 5: TBD

Environment: Preact, Typescript, Vite.

# Goal 1

Palm-lite is confirmed to work in the browser. It hasn't got dependencies that are not Node or Browser compatible.

+ [x] Palm-lite 
  + [x] Text Completion
  + [x] Chat
  + [x] Embedding

# Goal 2 - Build a web app that creates a breadboard programatically and runs it (using Starter Kit)

The simplest demo that does something useful should call the Palm API. The demo should request the API key, 

+ [ ] Create a breadboard
  + [x] Add the Starter Kit
  + [ ] Use API_Key Secrets: FAIL - the code in secrets.ts uses `process` which is not available to the browser `    .map((key) => [key, process.env[key]])`. You can make an global though.

```
window.process = {};
window.process.env = {};
window.process.env.API_KEY = apiKey;
```

# Goal 3

Broadly works if you remove the references to `kits` which can't currently be loaded.

Update: now that the kit is published, might be easier.

# Goal 4

1. To load a graph I need to use a `breadboard`. 
  `import { Board, type ProbeEvent } from "@google-labs/breadboard";` causes an error because it relies on an `readFile` from `fs/promise` [here](https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/src/board.ts#L31). It is only used if we provide a path to `loadGraph`, Remove the import and dynamically import readFile only when a file path is included:
  ```
  export const loadGraph = async (path?: string, ref?: string) => {
    if (path) { 
       const { readFile } = await import("node:fs/promise")
       return JSON.parse(await readFile(path, "utf-8"));
    }
    if (!ref) throw new Error("To include, we need a path or a $ref");
    const response = await fetch(ref);
    return await response.json();
  };
  ```
  Update: Tested and it stops the error.

2. KitLoader fails to dynamically import using vite as a bundler. When people are building sites they tend to use a bundler, and the bundler has to know about all the assets it needs to compile. I was trying `simplest.json` and it includes a kit `"url": "npm:@google-labs/llm-starter"` which will not be able to be loaded in the browser because the bundler 1) doesn't know about it, and 2) if we changed it to "http:" for a dynamic import we'd need to host it some where.
  * Note: maybe just copy it in for now?
  * Update: URLs have to be "Npm spec"... weird.

**Comment by dglazkov** [comment]
Could Goal 2 be #49?

**Comment by PaulKinlan** [comment]
> Could Goal 2 be #49?

Yes, I think it could.

**Comment by dglazkov** [comment]
@PaulKinlan  is this done?

**Comment by dglazkov** [comment]
🥳
