### ISSUE TITLE
If I have multiple kits, and they have a function with the same name... how do I use them both in the graph json?

### ISSUE THREAD

**Issue by PaulKinlan** [google/labs-prototypes#60]
Say I am creating a kit that happens to use the same node names as another kit, and there is a user with a graph that is using `@google-labs/llm-starter` and my new `kinlan-kit`. How would a user disambiguate the using a node on my kit vs the other.

For example, `text-completion` is a pretty common name that I could imagine a OpenAI kit might use. Using the API's `addKit` directly then all is good because I can access the reference. However, if I am using the JSON format then based off this [line](https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/src/board.ts#L66) it looks like the last kit registered wins the naming war...

It might be worth thinking about an optional namespacing of the kits in the JSON file that can be used to point to the correct kit's function.

e.g, 
```
"nodes": [
    {
      "id": "prompt-template-1",
      "type": "@llm-starter/prompt-template",
      ...
```

**Comment by dglazkov** [comment]
This was the idea for `using` qualifier in `KitDescriptor`.

**Comment by dglazkov** [comment]
Duping against #142
