### ISSUE TITLE
Create a `node-nursery` package for nascent node implementations

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#65]
To separate nodes we ship in LLM Starter Kit and nodes we're planning to ship but haven't quite settled into what they will be when they grow up, let's create a new package called `node-nursery` and move the nascent nodes there.

My intuition is that `node-nursery` is a forever-private package, and we graduate nodes from it to `llm-starter`.

**Comment by dglazkov** [comment]
@seefeldb I want to move semantic retrieval bits to `node-nursery`, for example.

**Comment by seefeldb** [comment]
Missed this before my comment. Assigning to myself.

**Comment by seefeldb** [comment]
@dglazkov should we remove local-memory as well, given #59 ?

**Comment by dglazkov** [comment]
I can't just remove it -- it's necessary for basic demos. What we could do instead try to push for #59 (adder) to be in M0?

**Comment by dglazkov** [comment]
Stick a fork in it 🥳
