### ISSUE TITLE
Distinguish wires that carry data from those that carry capabilities

### ISSUE THREAD

**Issue by seefeldb** [google/labs-prototypes#86]
In e.g. [graph-playground/graphs/find-file-by-similarity.json](https://github.com/google/labs-prototypes/blob/main/seeds/graph-playground/graphs/find-file-by-similarity.json), we're passing `cache` and `db` around, which aren't pure data but represent a disk-based cache and a memory-based vector database. We'd do something like that for other databases and services and many other ... capabilities.

This works transparently – we're just passing javascript objects around – but it will be useful to distinguish these at some point. E.g. Integrity checks requires understanding all data flows and capabilities create new otherwise possibly hidden ones (see e.g. #55). They also don't serialize, rollback state, etc. without extra help, so we'll need that for #7 and others.

**Comment by seefeldb** [comment]
To add a bit more here on what distinguishes capabilities from generic handles:

They can be more finer grained scope of what is allowed or not. For example read-only, only access to a subset of the data, etc.

And we might want to be able to scope down a capability when passing it to a node, e.g. turn a read-write capability into a read only one.

All future stuff though, for now let's just do handles. But maybe already wrapped in a `Capability<Kind>` class, so that data is either JSON, a Blob or this? (Or maybe it'll have to JSON extended by the ability for some fields to be either Blob or this?)

**Comment by dglazkov** [comment]
Yeah, I really like that. What should be the type definition here? How would it serialize?

**Comment by seefeldb** [comment]
Serializing: You mean in a future node definition?

Capabilities don't serialize over the wire, at least not without extra work that will be highly dependent on the capability.

As for typing, maybe as simple as Capability<T> that for now has a single field of type T? Or maybe it extends T and adds a dummy optional field `Symbol()` that we for now never use.

**Comment by dglazkov** [comment]
Initial implementation landed in 77fc02c288354f8e461ff1a47a3b267eaa2e7bf5.

More work to do, let's track as separate issues, etc.
