### ISSUE TITLE
Run breadboard as cloud function

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#88]
1. Take the graph json file
2. Take inputs
3. Produce outputs.

Could be neat to make it super-easy. As close to one-click as possible.

**Comment by PaulKinlan** [comment]
I'd be happy to put a cut down version of https://github.com/paulkinlan/tldr.site in seeds as a  starter kit for vercel. I'd also imagine it's pretty simple to get working in firebase too given they support Node 20.

**Comment by dglazkov** [comment]
@proales do you want to look into this one?

**Comment by dglazkov** [comment]
As of https://github.com/google/labs-prototypes/commit/8d74f2acf36b834e61a89833c7568b65755c073c, we can run Cloud Functions from a URL, and all the secrets are managed correctly.
