### ISSUE TITLE
Consider the concept of data bus

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#91]
When we start transferring blobs over the wire, it seems like we'll need something other than the current setup. Following the computer analogy, the concept of data bus might be interesting: a common infrastructure (probably part of the `Board`) that flexibly allows transfer of typed data.

**Comment by seefeldb** [comment]
See also #86 

`Blob`, especially immutable `Blob` should work for many cases though, no?

**Comment by dglazkov** [comment]
Maybe it's a matter of implementing something like transferable semantics for wires?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects

Node has support for transferables, too:

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects

and Blobs:
https://nodejs.org/dist/latest-v18.x/docs/api/buffer.html#class-blob

**Comment by dglazkov** [comment]
Closing as duplicate of #24
