### ISSUE TITLE
Output nodes should include meta data about the node (e.g, id)

### ISSUE THREAD

**Issue by PaulKinlan** [google/labs-prototypes#92]
When I was building https://tldr-site.vercel.app/news ([Graph](https://github.com/PaulKinlan/tldr.site/blob/main/graphs/search-summary.json) and [How I collect the data](https://github.com/PaulKinlan/tldr.site/blob/0852db47f211353ab22ed02f4e1d24302cbb058b/src/routes/home.tsx#L30)) I found it hard to reason about which output nodes where which.... Now in this app, I inferred it because 1) I knew Search Results are collected before Text Generation, and 2) the JSON properties are unique to each response. However I can easily imagine a scenario where a developer would not be able to tell which part of the graph a result came from.

It might be useful to have some data on the output result that includes the `id` of the node doing the outputting in some way (I recognize it might not be possible to just put `id` on to the object given that it just passes through what it recieved)

## Steps to Reproduce the Problem

1. Create a graph with two output nodes
1. Look at the results and see that it's hard to distinguish from whence the output came

**Comment by seefeldb** [comment]
You can control the names of the outputs by changing the arriving name on output nodes, which might be good API design for graphs, i.e. thinking about it as an abstraction that should be self explainable. This doesn't work for * though.

That said, there is a related meta data question: Some outputs might only come if certain inputs were present. The same graph might indeed have a number of input/output pairs like this, and one has to carefully study the graph to figure out how they pair up.

So this maps into a broader topic of graphs exporting node shaped interfaces. This could be single nodes in the graph, subgraphs, etc. Essentially graphs as kits. @dglazkov ?

**Comment by dglazkov** [comment]
> It might be useful to have some data on the output result that includes the id of the node doing the outputting in some way

WDYT about exposing the `NodeDescriptor` on `BreadboardRunResult`? This way, we should always be able to see what output or input node interrupted the run.

**Comment by seefeldb** [comment]
A step towards interrupts? #66

**Comment by PaulKinlan** [comment]
> WDYT about exposing the NodeDescriptor on BreadboardRunResult? This way, we should always be able to see what output or input node interrupted the run.

That'd work

**Comment by dglazkov** [comment]
See example in https://github.com/google/labs-prototypes/blob/d4aa34474a28da30a275d90463c17eb74cedc8f9/seeds/coffee-bot-board/src/cli.ts#L44
